export const routes = {
  AUTH_STACK: 'AUTH_STACK',
  MAIN_STACK: 'MAIN_STACK',

  WELCOME_SCREEN: 'WELCOME_SCREEN',

  LOGIN_SCREEN: 'LOGIN_SCREEN',
  REGISTER_SCREEN: 'REGISTER_SCREEN',

  HOME_SCREEN: 'HOME_SCREEN',
  MOVIES_SCREEN: 'MOVIES_SCREEN',
  PROFILE_SCREEN: 'PROFILE_SCREEN',
};
